ALTER TABLE actor DISABLE TRIGGER ALL;
ALTER TABLE actormember DISABLE TRIGGER ALL;
ALTER TABLE arch_connector_instance DISABLE TRIGGER ALL;
ALTER TABLE arch_document_mapping DISABLE TRIGGER ALL;
ALTER TABLE arch_flownode_instance DISABLE TRIGGER ALL;
ALTER TABLE arch_process_comment DISABLE TRIGGER ALL;
ALTER TABLE arch_process_instance DISABLE TRIGGER ALL;
ALTER TABLE command DISABLE TRIGGER ALL;
ALTER TABLE connector_instance DISABLE TRIGGER ALL;
ALTER TABLE dependencymapping DISABLE TRIGGER ALL;
ALTER TABLE event_trigger_instance DISABLE TRIGGER ALL;
ALTER TABLE flownode_instance DISABLE TRIGGER ALL;
ALTER TABLE form_mapping DISABLE TRIGGER ALL;
ALTER TABLE job_desc DISABLE TRIGGER ALL;
ALTER TABLE job_log DISABLE TRIGGER ALL;
ALTER TABLE page_mapping DISABLE TRIGGER ALL;
ALTER TABLE pending_mapping DISABLE TRIGGER ALL;
ALTER TABLE platform DISABLE TRIGGER ALL;
ALTER TABLE process_comment DISABLE TRIGGER ALL;
ALTER TABLE process_content DISABLE TRIGGER ALL;
ALTER TABLE process_definition DISABLE TRIGGER ALL;
ALTER TABLE process_instance DISABLE TRIGGER ALL;
ALTER TABLE processsupervisor DISABLE TRIGGER ALL;
ALTER TABLE profile DISABLE TRIGGER ALL;
ALTER TABLE profileentry DISABLE TRIGGER ALL;
ALTER TABLE profilemember DISABLE TRIGGER ALL;
ALTER TABLE QRTZ_CRON_TRIGGERS DISABLE TRIGGER ALL;
ALTER TABLE QRTZ_LOCKS DISABLE TRIGGER ALL;
ALTER TABLE QRTZ_SCHEDULER_STATE DISABLE TRIGGER ALL;
ALTER TABLE QRTZ_SIMPLE_TRIGGERS DISABLE TRIGGER ALL;
ALTER TABLE queriable_log DISABLE TRIGGER ALL;
ALTER TABLE sequence DISABLE TRIGGER ALL;
ALTER TABLE user_ DISABLE TRIGGER ALL;
ALTER TABLE user_login DISABLE TRIGGER ALL;
ALTER TABLE waiting_event DISABLE TRIGGER ALL;

TRUNCATE SEQUENCE CASCADE;
TRUNCATE TABLE QUERIABLE_LOG CASCADE;
TRUNCATE TABLE PROFILE CASCADE;
TRUNCATE TABLE QRTZ_LOCKS CASCADE;
TRUNCATE TABLE PLATFORM CASCADE;
TRUNCATE TABLE JOB_DESC CASCADE;

copy actor from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\actor.csv' DELIMITER '|' CSV NULL '';
copy actormember from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\actormember.csv' DELIMITER '|' CSV NULL '';
copy arch_document_mapping from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\arch_document_mapping.csv' DELIMITER '|' CSV NULL '';
copy arch_flownode_instance from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\arch_flownode_instance.csv' DELIMITER '|' CSV NULL '';
copy arch_process_comment from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\arch_process_comment.csv' DELIMITER '|' CSV NULL '';
copy arch_process_instance from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\arch_process_instance.csv' DELIMITER '|' CSV NULL '';
copy connector_instance from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\connector_instance.csv' DELIMITER '|' CSV NULL '';
copy dependencymapping from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\dependencymapping.csv' DELIMITER '|' CSV NULL '';
copy event_trigger_instance from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\event_trigger_instance.csv' DELIMITER '|' CSV NULL '';
copy flownode_instance from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\flownode_instance.csv' DELIMITER '|' CSV NULL '';
copy form_mapping from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\form_mapping.csv' DELIMITER '|' CSV NULL '';
copy job_desc from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\job_desc.csv' DELIMITER '|' CSV NULL '';
copy pending_mapping from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\pending_mapping.csv' DELIMITER '|' CSV NULL '';
copy platform from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\platform.csv' DELIMITER '|' CSV NULL '';
copy process_comment from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\process_comment.csv' DELIMITER '|' CSV NULL '';
copy process_definition from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\process_definition.csv' DELIMITER '|' CSV NULL '';
copy process_instance from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\process_instance.csv' DELIMITER '|' CSV NULL '';
copy processsupervisor from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\processsupervisor.csv' DELIMITER '|' CSV NULL '';
copy profile from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\profile.csv' DELIMITER '|' CSV NULL '';
copy profileentry from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\profileentry.csv' DELIMITER '|' CSV NULL '';
copy profilemember from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\profilemember.csv' DELIMITER '|' CSV NULL '';
copy QRTZ_CRON_TRIGGERS from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\QRTZ_CRON_TRIGGERS.csv' DELIMITER '|' CSV NULL '';
copy QRTZ_LOCKS from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\QRTZ_LOCKS.csv' DELIMITER '|' CSV NULL '';
copy QRTZ_SCHEDULER_STATE from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\QRTZ_SCHEDULER_STATE.csv' DELIMITER '|' CSV NULL '';
copy QRTZ_SIMPLE_TRIGGERS from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\QRTZ_SIMPLE_TRIGGERS.csv' DELIMITER '|' CSV NULL '';
copy queriable_log from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\queriable_log.csv' DELIMITER '|' CSV NULL '';
copy sequence from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\sequence.csv' DELIMITER '|' CSV NULL '';
copy user_ from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\user_.csv' DELIMITER '|' CSV NULL '';
copy user_login from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\user_login.csv' DELIMITER '|' CSV NULL '';
copy waiting_event from 'C:\projects\119-migrationToPostgresql\csvOutputCFDT\waiting_event.csv' DELIMITER '|' CSV NULL '';

ALTER TABLE actor ENABLE TRIGGER ALL;
ALTER TABLE actormember ENABLE TRIGGER ALL;
ALTER TABLE arch_connector_instance ENABLE TRIGGER ALL;
ALTER TABLE arch_document_mapping ENABLE TRIGGER ALL;
ALTER TABLE arch_flownode_instance ENABLE TRIGGER ALL;
ALTER TABLE arch_process_comment ENABLE TRIGGER ALL;
ALTER TABLE arch_process_instance ENABLE TRIGGER ALL;
ALTER TABLE command ENABLE TRIGGER ALL;
ALTER TABLE connector_instance ENABLE TRIGGER ALL;
ALTER TABLE dependencymapping ENABLE TRIGGER ALL;
ALTER TABLE event_trigger_instance ENABLE TRIGGER ALL;
ALTER TABLE flownode_instance ENABLE TRIGGER ALL;
ALTER TABLE form_mapping ENABLE TRIGGER ALL;
ALTER TABLE job_desc ENABLE TRIGGER ALL;
ALTER TABLE job_log ENABLE TRIGGER ALL;
ALTER TABLE pending_mapping ENABLE TRIGGER ALL;
ALTER TABLE platform ENABLE TRIGGER ALL;
ALTER TABLE process_comment ENABLE TRIGGER ALL;
ALTER TABLE process_content ENABLE TRIGGER ALL;
ALTER TABLE process_definition ENABLE TRIGGER ALL;
ALTER TABLE process_instance ENABLE TRIGGER ALL;
ALTER TABLE processsupervisor ENABLE TRIGGER ALL;
ALTER TABLE profile ENABLE TRIGGER ALL;
ALTER TABLE profileentry ENABLE TRIGGER ALL;
ALTER TABLE profilemember ENABLE TRIGGER ALL;
ALTER TABLE QRTZ_CRON_TRIGGERS ENABLE TRIGGER ALL;
ALTER TABLE QRTZ_LOCKS ENABLE TRIGGER ALL;
ALTER TABLE QRTZ_SCHEDULER_STATE ENABLE TRIGGER ALL;
ALTER TABLE QRTZ_SIMPLE_TRIGGERS ENABLE TRIGGER ALL;
ALTER TABLE queriable_log ENABLE TRIGGER ALL;
ALTER TABLE sequence ENABLE TRIGGER ALL;
ALTER TABLE user_ ENABLE TRIGGER ALL;
ALTER TABLE user_login ENABLE TRIGGER ALL;
ALTER TABLE waiting_event ENABLE TRIGGER ALL;

